#!/usr/bin/python
# Only used for testing without installing.

import os
import sys

def main2():
  root_dir = os.path.dirname(os.path.abspath(__file__))
  sys.path.insert(0, os.path.join(root_dir, 'src'))
  from landslide.main import main
  main()

main2()
